/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

import (
	"encoding/json"
	"net/http"
	"os"
)

var Emsps []Emsp

func ReadEmsps(file string) ([]Emsp, error) {
	// Read emsp file and return 500 response if failed
	data, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}

	// JSON serialize emsps array
	var emsps []Emsp
	err = json.Unmarshal(data, &emsps)
	if err != nil {
		return nil, err
	}

	return emsps, nil
}

func GetEmsps(w http.ResponseWriter, r *http.Request) {
	data, err := json.Marshal(Emsps)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	// Write file content into HTTP response
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Write(data)
	w.WriteHeader(http.StatusOK)
}
