/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type AuthorizationDetail struct {
	ChargingPeriod *AuthorizationOptionsChargingPeriod `json:"chargingPeriod,omitempty"`

	MaximumAmount *CurrencyAmount `json:"maximumAmount,omitempty"`

	MaximumTransactionAmount *CurrencyAmount `json:"maximumTransactionAmount,omitempty"`
}
