/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type AuthorizationResponse struct {
	RequestUri string `json:"request_uri"`

	State string `json:"state"`
}
