/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type AuthorizationRequest struct {
	EmspId string `json:"emsp_id,omitempty"`

	Detail *AuthorizationDetail `json:"detail,omitempty"`
}
