/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type Emsp struct {
	Id string `json:"id"`

	Name string `json:"name"`

	BaseUrl string `json:"base_url"`

	ClientId string `json:"client_id"`

	Image string `json:"image,omitempty"`
}
