/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

import (
	"time"
)

type AuthorizationOptionsChargingPeriod struct {
	Start time.Time `json:"start"`

	End time.Time `json:"end"`
}
