/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type CurrencyAmount struct {
	Amount string `json:"amount"`

	Currency string `json:"currency"`
}
