/*
 * eMSP Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	emsp_backend "emsp_backend/go"
)

func main() {
	log.Printf("Starting server...")

	// Load Configuration
	err := emsp_backend.LoadConfiguration()
	if err != nil {
		log.Fatalf("Loading failed: " + err.Error())
		return
	}

	// Load JWKS
	log.Printf("Loading JWKS...")
	err = emsp_backend.LoadJwks(emsp_backend.Configuration.JwksUri)
	if err != nil {
		log.Fatalf("Failed to load JWKS: " + err.Error())
		return
	}
	log.Printf("JWKS loaded")

	// Initialize Router
	router := emsp_backend.NewRouter()

	log.Printf("Server started")

	// Start HTTP Server
	log.Fatal(http.ListenAndServe(":"+emsp_backend.Configuration.Port, router))
}
