/*
 * EV Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ev_backend

type AuthorizationDetail struct {
	Type string `json:"type"`

	Actions []string `json:"actions"`

	Locations []string `json:"locations"`

	ChargingPeriod *ChargingPeriod `json:"charging_period"`

	MaximumAmount *CurrencyAmount `json:"maximum_amount"`

	MaximumTransactionAmount *CurrencyAmount `json:"maximum_transaction_amount"`
}
