/*
 * eMSP Backend
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_backend

import (
	"errors"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path"
	"strings"

	"github.com/golang-jwt/jwt"
	"github.com/google/uuid"
)

func GetTokenKey(token *jwt.Token) (interface{}, error) {
	// Get key ID from token header
	keyId := token.Header["kid"].(string)
	if keyId == "" {
		return nil, errors.New("Token header does not contain a Key ID ('kid')")
	}

	// Get Key from JWKS Store
	keyPtr := GetKey(keyId)
	if keyPtr == nil {
		return nil, errors.New("Key with KeyID '" + keyId + "' not found")
	}

	// Convert key to binary
	var key interface{}
	(*keyPtr).Raw(&key)

	return key, nil
}

func ValidateAuthorization(r *http.Request) error {
	// Get Authorization Header
	authorizationHeader := r.Header.Get("authorization")
	if authorizationHeader == "" {
		return errors.New("No Authorization Header present")
	}

	// Get Bearer Token from Authorization Header
	bearerHeader := strings.Split(authorizationHeader, " ")
	if len(bearerHeader) != 2 {
		return errors.New("Invalid Authorization Header")
	}
	if strings.ToLower(bearerHeader[0]) != "bearer" {
		return errors.New("Expected Bearer Token")
	}

	// Parse Access Token
	claims := jwt.MapClaims{}
	accessToken, err := jwt.ParseWithClaims(bearerHeader[1], claims, GetTokenKey)
	if err != nil {
		return errors.New("Access Token validation failed")
	}

	// Verify that token is valid
	if !accessToken.Valid {
		return errors.New("Access Token not valid")
	}
	// Verify issuer
	if !claims.VerifyIssuer(Configuration.TrustedIssuer, true) {
		issuer := claims["iss"].(string)
		return errors.New("Untrusted Issuer '" + issuer + "'")
	}
	// Verify audience
	if !claims.VerifyAudience(Configuration.TrustedIssuer, true) {
		audience := claims["aud"].(string)
		return errors.New("Invalid audience '" + audience + "'")
	}
	// Verify time validity
	if err = claims.Valid(); err != nil {
		return errors.New("Access Token claims are not valid: " + err.Error())
	}
	// Verify scope
	scopes := strings.Split(claims["scopes"].(string), " ")
	err = ScopesValid(scopes)
	if err != nil {
		return errors.New("Access Token is missing Scopes: " + err.Error())
	}

	// TODO: Validate rich authorization

	return nil
}

func DownloadCsr(r *http.Request) (string, error) {
	// Create CSR Directory if not exists
	_, err := os.Stat(Configuration.CsrDirectory)
	if os.IsNotExist(err) {
		err = os.Mkdir(Configuration.CsrDirectory, 0755)
		if err != nil {
			return "", errors.Join(errors.New("Failed to create CSR Directory"), err)
		}
	} else if err != nil {
		return "", errors.New("Failed to access CSR Directory")
	}

	// Prepare CSR ID, file name, and file path
	csrId := uuid.NewString()
	csrFileName := csrId + ".csr"
	csrFilePath := path.Join(Configuration.CsrDirectory, csrFileName)

	// Create CSR File
	csrFile, err := os.Create(csrFilePath)
	if err != nil {
		return "", errors.Join(errors.New("Failed to create CSR File '"+csrFilePath+"'"), err)
	}
	defer csrFile.Close()

	// Copy HTTP CSR Body from HTTP POST Body to CSR File
	_, err = io.Copy(csrFile, r.Body)
	if err != nil {
		return "", errors.Join(errors.New("Failed to download CSR to '"+csrFilePath+"'"), err)
	}

	return csrId, nil
}

func SignCsr(csrPath string, crtPath string) error {
	// Prepare signing command
	var signingArgs []string

	for i := 0; i < len(Configuration.SigningArgs); i++ {
		arg := signingArgs[i]
		arg = strings.ReplaceAll(arg, "${CSR_FILE}", csrPath)
		arg = strings.ReplaceAll(arg, "${CRT_FILE}", crtPath)
		signingArgs = append(signingArgs, arg)
	}

	// Sign downloaded CSR
	cmd := exec.Command(Configuration.SigningCommand, signingArgs...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		return errors.Join(errors.New("Failed to sign CSR"), err)
	}

	return nil
}

func SendCrt(crtPath string, w *http.ResponseWriter) error {
	crtFile, err := os.Open(crtPath)
	if err != nil {
		return errors.Join(errors.New("Failed to open CRT File"), err)
	}
	defer crtFile.Close()

	_, err = io.Copy((*w), crtFile)
	if err != nil {
		return errors.Join(errors.New("Failed to copy CRT File"), err)
	}

	return nil
}

func PostCsr(w http.ResponseWriter, r *http.Request) {
	// Validate authorization
	err := ValidateAuthorization(r)
	if err != nil {
		log.Printf(err.Error())
		w.WriteHeader(http.StatusUnauthorized)
		return
	}

	// Validate Content Type
	contentType := r.Header.Get("content-type")
	if contentType != "application/pkcs10" {
		log.Printf("Invalid Content Type")
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	// Download CSR from HTTP POST Body to new CSR File
	csrId, err := DownloadCsr(r)
	if err != nil {
		log.Printf(err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	// Prepare CSR Path
	csrFile := csrId + ".csr"
	csrPath := path.Join(Configuration.CsrDirectory, csrFile)

	// Prepare CRT Path
	crtFile := csrId + ".crt"
	crtPath := path.Join(Configuration.CrtDirectory, crtFile)

	// Sign CSR
	err = SignCsr(csrPath, crtPath)
	if err != nil {
		log.Printf(err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	// Send CRT File in response body
	err = SendCrt(crtPath, &w)
	if err != nil {
		log.Printf(err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/x-x509-user-cert; charset=UTF-8")
	w.WriteHeader(http.StatusCreated)
}
