/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	emsp_as "emsp_as/go"
)

func main() {
	log.Printf("Starting server...")

	// Load Configuration
	err := emsp_as.LoadConfiguration()
	if err != nil {
		log.Fatalf("Loading failed: " + err.Error())
		return
	}

	// Initialize Router
	router := emsp_as.NewRouter()

	log.Printf("Server started")

	// Start HTTP Server
	log.Fatal(http.ListenAndServe(":"+emsp_as.Configuration.Port, router))
}
