/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

type PushedAuthorizationRequest struct {
	ResponseType         string                `json:"response_type"`
	RedirectUri          string                `json:"redirect_uri"`
	Scope                string                `json:"scope"`
	ClientId             string                `json:"client_id"`
	State                string                `json:"state,omitempty"`
	CodeChallenge        string                `json:"code_challenge"`
	CodeChallengeMethod  string                `json:"code_challenge_method"`
	AuthorizationDetails []AuthorizationDetail `json:"authorization_details"`
}
