/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

type PushedAuthorizationRequest struct {
	ResponseType         *ResponseType          `json:"response_type"`
	RedirectUri          string                 `json:"redirect_uri"`
	Scope                string                 `json:"scope"`
	State                string                 `json:"state,omitempty"`
	CodeChallenge        string                 `json:"code_challenge"`
	CodeChallengeMethod  *CodeChallengeMethod   `json:"code_challenge_method"`
	ClientId             string                 `json:"client_id"`
	ClientSecret         string                 `json:"client_secret"`
	AuthorizationDetails *[]AuthorizationDetail `json:"authorization_details,omitempty"`
}
