/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

import (
	"time"
)

type AuthorizationRequest struct {
	ScopesGranted              bool       `json:"scopes_granted"`
	Actions                    *[]Action  `json:"actions"`
	ChargingPeriodStart        *time.Time `json:"charging_period_start"`
	ChargingPeriodEnd          *time.Time `json:"charging_period_end"`
	MaximumAmount              string     `json:"maximum_amount"`
	MaximumCurrency            *Currency  `json:"maximum_currency"`
	MaximumTransactionAmount   string     `json:"maximum_transaction_amount"`
	MaximumTransactionCurrency *Currency  `json:"maximum_transaction_currency"`
}
