/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

type AuthorizationDetail struct {
	Type                     string          `json:"type"`
	Actions                  *[]Action       `json:"actions"`
	Locations                []string        `json:"locations"`
	ChargingPeriod           *ChargingPeriod `json:"chargingPeriod"`
	MaximumAmount            *CurrencyAmount `json:"maximumAmount"`
	MaximumTransactionAmount *CurrencyAmount `json:"maximumTransactionAmount"`
}
