/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

type CodeChallengeMethod string

// List of CodeChallengeMethod
const (
	S256 CodeChallengeMethod = "S256"
)
