/*
 * eMSP Authorization Server
 *
 * Authorization Server of an e-Mobility Service Provider written in Go.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package emsp_as

type PushedAuthorizationResponse struct {
	// The Request URI of a Pushed Authorization Request.
	RequestUri string `json:"request_uri"`

	// Lifetime of Request URI in seconds.
	ExpiresIn int16 `json:"expires_in"`
}
