openapi: 3.0.3
info:
  title: EV Backend
  description: Backend of the EV written in Go.
  version: 0.1.0
servers:
  - url: http://localhost:8080
  - url: http://ev.localhost
tags:
  - name: Discovery
    description: Endpoints related to discover relevant information.
  - name: Authorization
    description: Endpoints related to the OAuth Authorization Flow.
paths:
  /emsps:
    get:
      tags:
        - Discovery
      summary: Gets supported eMSPs
      description: Returns an array of supported eMSP infos.
      operationId: getEmsps
      responses:
        "200":
          description: List of eMSPs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Emsp'
                x-content-type: application/json
        "500":
          description: Internal server error
  /cpr:
    post:
      tags:
        - Authorization
      summary: Receives Contract Provisioning Request which initializes the authorization flow
      description: Transfers the desired eMSP and authorization parameters.
      operationId: requestContractProvisioning
      requestBody:
        $ref: '#/components/requestBodies/ContractProvisioningRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractProvisioningResponse'
        "400":
          description: Bad request
        "404":
          description: eMSP ID not found
        "500":
          description: Internal server error
  /confirm:
    post:
      tags:
        - Authorization
      summary: Finishes the authorization
      description: Transfers the Authorization Code to the EV which finishes the authorization process.
      operationId: confirmAuthorization
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationRequest'
      responses:
        "200":
          description: OK
        "404":
          description: Unknown state
        "500":
          description: Internal server error
components:
  schemas:
    Emsp:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EmspId'
        name:
          type: string
          example: OpenIDCharge
        base_url:
          type: string
          format: uri
          example: https://as.example.com/
        image:
          type: string
          format: uri
      required:
        - id
        - name
        - base_url
      example:
        id: oidcharge
        name: OpenIDCharge
        base_url: https://as.example.com/
    EmspId:
      type: string
      example: oidcharge
    ContractProvisioningRequest:
      type: object
      properties:
        emsp_id:
          $ref: '#/components/schemas/EmspId'
        redirect_uri:
          type: string
          format: uri
          example: https://ua.example.com/redirect
        authorization_detail:
          $ref: '#/components/schemas/AuthorizationDetail'
      required:
        - emsp_id
        - redirect_uri
        - authorization_detail
    AuthorizationDetail:
      type: object
      properties:
        type:
          type: string
          example: "pnc_contract_request"
        charging_period:
          $ref: '#/components/schemas/ChargingPeriod'
        maximum_amount:
          $ref: '#/components/schemas/CurrencyAmount'
        maximum_transaction_amount:
          $ref: '#/components/schemas/CurrencyAmount'
      required:
        - type
        - charging_period
        - maximum_amount
        - maximum_transaction_amount
    ChargingPeriod:
      type: object
      properties:
        start:
          type: string
          format: date-time
          example: 2023-09-07T14:00:00Z
        end:
          type: string
          format: date-time
          example: 2023-10-07T15:00:00Z
      required:
        - start
        - end
    CurrencyAmount:
      type: object
      properties:
        amount:
          type: string
          format: decimal
          example: "123.50"
        currency:
          $ref: '#/components/schemas/Currencies'
      required:
        - amount
        - currency
    Currencies:
      type: string
      enum:
       - EUR
       - USD
      example: EUR
    ContractProvisioningResponse:
      type: object
      properties:
        request_uri:
          $ref: '#/components/schemas/RequestUri'
        client_id:
          $ref: '#/components/schemas/ClientId'
        state:
          $ref: '#/components/schemas/State'
      required:
        - request_uri
        - client_id
        - state
    RequestUri:
      type: string
      description: The Request URI of a Pushed Authorization Request.
      format: uri
      example: urn:example:bwc4JK-ESC0w8acc191e-Y1LTC2
    ClientId:
      type: string
      example: oidcharge
    State:
      type: string
      example: OcnS3ace5b
    ConfirmationRequest:
      type: object
      properties:
        auth_code:
          type: string
          example: LRS7CLedX3ws5fiJO4KenKe
        state:
          $ref: '#/components/schemas/State'
      required:
        - auth_code
        - state
  requestBodies:
    ContractProvisioningRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ContractProvisioningRequest'
    ConfirmationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfirmationRequest'
